### ISSUE TITLE
Beachball when viewing large file with no wrap

### ISSUE THREAD

**Issue by nicpottier** [google/xi-mac#200] opened 2018-06-08 22:47 UTC
1. Set `word_wrap` to false, set `wrap_width` to 0
2. Load attached file. (rename to `.xml`)

Expected:
File loaded on a single line.

Actual:
Beach ball.

I can repro in XCode and stop it but not sure what to share here.

**Comment by nicpottier** [comment] 2018-06-08 22:47
[contact_export_19.xml.txt](https://github.com/google/xi-mac/files/2086386/contact_export_19.xml.txt)

**Comment by cmyr** [comment] 2018-06-08 22:53
Okay thanks nic will take a look at this.

**Comment by cmyr** [comment] 2018-06-09 14:52
Ah yea this is a dupe of #20. I'm not sure how best to handle this; we may want to have some heuristic in xi-mac where we don't try to compute the full width of a line that exceeds some threshold length?

**Closed by cmyr** 2018-06-09 14:52 UTC
