### ISSUE TITLE
[UI Bug] Find menu is transparent when opening more than one file in a session

### ISSUE THREAD

**Issue by HazemAlhalabi** [google/xi-mac#258] opened 2018-09-15 16:31 UTC
The find menu (⌘+F) has the correct background color for the first file I open in a session, but every subsequent file I open has a transparent find menu.

I was able to replicate this issue every time I restarted Xi. I'm running the current version.

This might be relevant: https://github.com/google/xi-mac/issues/194#issuecomment-408353412

Thanks!

**Comment by jansol** [comment] 2018-09-15 16:50
FWIW I can't seem to reproduce this. (xi-mac 1fa66c82, macOS 10.13.6)

**Comment by HazemAlhalabi** [comment] 2018-09-15 17:45
Weird. I'm running the same version of xi-mac and macOS as @jansol 
I just cloned another copy of xi-mac and built it. The same issue persists. 

The first file I open has the correct background color for the find menu. Every subsequent file I open has a transparent menu. I attached a screenshot to show what it looks like:
![screen shot 2018-09-15 at 1 40 20 pm](https://user-images.githubusercontent.com/8379135/45589071-6cfbc780-b8ed-11e8-953e-9c2c8148648f.png)

Can anyone else replicate the bug?

**Comment by jansol** [comment] 2018-09-15 17:50
Ah, you are *not* using the unified title bar, whereas I am. This used to be an issue *with* unified titlebar but that was fixed. Looks like it has regressed in the 'traditional' case at some point in the process.

**Comment by jansol** [comment] 2018-09-15 17:56
Hmm can't repro with `unified_titlebar = false` either. Could this be something like your theme cache being outdated or something? Does it still happen if you switch to another theme? Maybe also try a clean build.

**Comment by HazemAlhalabi** [comment] 2018-09-15 18:15
When I switch to another theme, the transparent find menus become correctly colored, but only for the windows that were already open. When I open another file and use the find menu again, it appears as transparent on that tab/window. See the attachment: (The top 2 windows were already open. When I switched the theme, the transparency issue was gone for those 2 windows. After switching the theme, I opened the third window at the bottom, which got a transparent find menu)
![screen shot 2018-09-15 at 2 03 45 pm](https://user-images.githubusercontent.com/8379135/45589226-425f3e00-b8f0-11e8-8bbc-d8898494513d.png)

As for the clean build, I have already cloned a fresh copy of xi-editor and xi-mac and built them in another directory, and the issue persists for me. I'm still new to xi but I'm assuming the themes are bundled with the app. Is there a separate theme cache elsewhere that I should try clearing?

**Comment by ryanbloom** [comment] 2018-09-15 19:16
I'm able to reproduce this if I completely delete the `unified_titlebar` line from my config file. Should be fixed in #259.

There's another a minor bug though: if you set `unified_titlebar = true`, then open some windows and delete that line, the windows don't update to the default appearance. Maybe the core should either send a default value or inform the frontend that it's been deleted.

**Comment by cmyr** [comment] 2018-09-16 00:51
yea `unified_toolbar` is weird because core doesn't know it exists, as a setting; that core will return arbitrary values to the client is really a bug, but it's been nice to have, and there hasn't been a real alternative, so it's stayed, but the behaviour isn't great.

Some of the config stuff could definitely do with a rethink; what we probably really want here is just a client namespace or something.

**Closed** 2018-09-17 16:01 UTC
Labels: UI, bug
