### ISSUE TITLE
Cannot open a text file, after trying to open a binary file

### ISSUE THREAD

**Issue by vors** [google/xi-mac#188] opened 2018-06-01 02:51 UTC
## Repro steps

1. Build `XiEditor.app` locally, start it.
2. Open a binary file thru the open menu. Nothing happens (assume it's not supported)
3. Try to open any text file.

## Expected

You should be able to open text file.

## Actually

Nothing happens when you try to open a text file.

**Comment by raphlinus** [comment] 2018-06-01 03:07
This is probably a panic caused by failing utf-8 validation. Grabbing log output would say for sure. In any case, the fix is no doubt to improve error handling, and maybe do something useful - opening the file in a hex mode would be a particularly developer-friendly action.

In any case, this is almost certainly a xi-editor issue rather than xi-mac.

**Comment by jansol** [comment] 2018-06-07 06:32
Tried reproducing, got a window without a gutter like I had at some point earlier. Nothing useful in the log file though...

**Comment by cmyr** [comment] 2018-06-07 14:12
I'm not able to reproduce? When I open a binary I see an error in the console about `"failed to load file"`  (which doesn't seem to be getting handled correctly) and I get a new blank window that isn't attached to core, but I can still open other windows.

We should definitely be surfacing the error the the user and closing the window, on the xi-mac side. On the core side we should make sure that we're sending the error correctly?

**Comment by cmyr** [comment] 2018-06-07 15:12
In any case in xi-mac we weren't handling error results at all; I've addressed this in #196. @vors I'd be curious to know what happens when you try that patch?

**Comment by vors** [comment] 2018-06-08 05:47
Hm, indeed I cannot repro it on master anymore: it loads the text file after the failure to load a binary one.
@cmyr thank you, yes, your patch works great

![image](https://user-images.githubusercontent.com/816680/41140884-b5d748cc-6aa4-11e8-8986-3ac838f69f0d.png)

**Comment by cmyr** [comment] 2018-06-08 20:12
@vors yep definitely room for improvement there, opened an issue in core to track. 😄.

**Closed** 2018-06-08 20:27 UTC
